global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Configurações de alerta (podem ser expandidas posteriormente)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Regras de alerta (podem ser expandidas posteriormente)
rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
    scrape_interval: 5s

  - job_name: "consumer"
    static_configs:
      - targets: ["consumer:9092"]
    scrape_interval: 5s

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 10s

  # Health endpoints para monitoramento
  - job_name: "health-checks"
    metrics_path: /health
    scrape_interval: 5s
    static_configs:
      - targets: 
          - "api:8000"
          - "consumer:8080" 