FROM openjdk:11-slim

# Variáveis de ambiente
ENV JMETER_VERSION=5.6.2
ENV JMETER_HOME=/opt/apache-jmeter-${JMETER_VERSION}
ENV JMETER_BIN=${JMETER_HOME}/bin
ENV PATH=${PATH}:${JMETER_BIN}

# Instalar utilitários necessários
RUN apt-get update && \
    apt-get -y install wget unzip curl && \
    mkdir -p /opt && \
    wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-${JMETER_VERSION}.zip && \
    unzip apache-jmeter-${JMETER_VERSION}.zip -d /opt && \
    rm apache-jmeter-${JMETER_VERSION}.zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Verificar a instalação
RUN jmeter --version

# Definir o diretório de trabalho
WORKDIR /jmeter

# Copiar arquivos de teste
COPY test-plans/ /jmeter/test-plans/
COPY scripts/ /jmeter/scripts/

# Tornar scripts executáveis
RUN chmod +x /jmeter/scripts/*.sh

# Porta para interface web, caso necessário
EXPOSE 4445

# Comando padrão (pode ser substituído durante a execução)
ENTRYPOINT ["/jmeter/scripts/run-tests.sh"] 